version: '3'

services: 
   rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbit-dev
      hostname: my-rabbit
      environment:
         RABBITMQ_DEFAULT_USER: admin
         RABBITMQ_DEFAULT_PASS: admin
      ports:
      - 15672:15672
      - 5672:5672
